### PR TITLE
Fix js compactor issues with regex etc.

### PR DESCRIPTION
**Pull request by trollkotze**
This addresses the points mentioned in https://github.com/splitbrain/dokuwiki/issues/3645

### CODE REVIEW

**Comment by splitbrain** [comment]
can you please add unit tests covering the issues this fixes?

**Comment by trollkotze** [comment]
Sorry, I'm not familiar with your unit testing. So it would be great if you could it up from here.
Last manual test I've done was to replace the `$js` input like this right before `js_compress` is called and looking at the results before and after.
An example plugin which includes a script ending with .min.js that was unnecessarily taken through the compactor (and then caused errors due to the regex stuff fixed here) is https://github.com/lisps/html5video/.

`
console.log('heya!');    const regexWithSlashInIt = /[+\-*/],/;
console.log(
  'This here is all considered part of a regex starting with the last slash'  ,
   'So the whitespace is not compacted until here: /', // and now this is considered to be part of a   string starting with single quote   that   single quote  earlier, so this one-line-comment won't be   stripped until   the apostrophe.
   // now all should be fine again but commented behind the double-slash of the previous comment that was taken to be part of a single quote string.
  );     console.log('Now everything should be fine again.');
  
// In the following line, the / / is contracted and the regex commented out by mistake.
const three = 3 / /asdf/.test('asdf');

const backtickery = ` this is text with spaces in it which should not be compacted \n
                      second line for good measure
                      the end`;




$js = "console.log('heya!');    const regexWithSlashInIt = /[+\-*/],/;
console.log(
  'This here is all considered part of a regex starting with the last slash'  ,
   'So the whitespace is not compacted until here: /', // and now this is considered to be part of a   string starting with single quote   that   single quote  earlier, so this one-line-comment won't be   stripped until   the apos>
   // now all should be fine again but commented behind the double-slash of the previous comment that was taken to be part of a single quote string.
  );     console.log('Now everything should be fine again.');
  
// In the following line, the / / is contracted and the regex commented out by mistake.
const three = 3 / /asdf/.test('asdf');

const backtickery = ` this    is   text    with spaces in   it which should not be compacted \n
                      but it will be
                      another line for good measure
                      the end`;

";
`

**Comment by splitbrain** [comment]
> Sorry, I'm not familiar with your unit testing

Looking at https://github.com/splitbrain/dokuwiki/blob/master/_test/tests/lib/exe/js_js_compress.test.php should make it relatively obvious on how to add tests. Even if you don't run them locally, github will run them for you on push. Thanks for your help.

**Comment by splitbrain** [comment]
I moved the compressor into its own repo, applied your patches and added tests. See also #3917

**Pull request closed without merging**
